# Generated by Django 4.1.3 on 2022-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_slug', models.SlugField(max_length=32)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_cost', models.PositiveIntegerField(default=0)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
