# Generated by Django 4.1.3 on 2022-11-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject_dz5', '0001_initial'),
        ('product_page', '0002_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject_dz5.category'),
        ),
    ]
